# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QFileDialog, QAction
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setAutoFillBackground(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(430, 0, 461, 41))

        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setObjectName("title")

        #Img load image
        self.img_original = QtWidgets.QLabel(self.centralwidget)
        self.img_original.setGeometry(QtCore.QRect(10, 80, 250, 250))
        self.img_original.setText("")
        self.img_original.setPixmap(QtGui.QPixmap("assets/img_test_detection3.jpeg"))
        self.img_original.setScaledContents(True)
        self.img_original.setObjectName("img_original")
        self.label_original = QtWidgets.QLabel(self.centralwidget)
        self.label_original.setGeometry(QtCore.QRect(70, 50, 151, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_original.setFont(font)
        self.label_original.setObjectName("label_original")
        self.buttonProcess = QtWidgets.QPushButton(self.centralwidget)
        self.buttonProcess.setGeometry(QtCore.QRect(270, 180, 90, 50))
        self.buttonProcess.setObjectName("buttonProcess")
        self.label_hsv = QtWidgets.QLabel(self.centralwidget)
        self.label_hsv.setGeometry(QtCore.QRect(420, 50, 151, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_hsv.setFont(font)
        self.label_hsv.setObjectName("label_hsv")

        self.img_hsv = QtWidgets.QLabel(self.centralwidget)
        self.img_hsv.setGeometry(QtCore.QRect(370, 80, 250, 250))
        self.img_hsv.setText("")
        self.img_hsv.setPixmap(QtGui.QPixmap("assets/img_test_detection3.jpeg"))
        self.img_hsv.setScaledContents(True)
        self.img_hsv.setObjectName("img_hsv")

        self.img_points = QtWidgets.QLabel(self.centralwidget)
        self.img_points.setGeometry(QtCore.QRect(640, 80, 250, 250))
        self.img_points.setText("")
        self.img_points.setPixmap(QtGui.QPixmap("assets/img_test_detection3.jpeg"))
        self.img_points.setScaledContents(True)
        self.img_points.setObjectName("img_points")

        self.label_puntos = QtWidgets.QLabel(self.centralwidget)
        self.label_puntos.setGeometry(QtCore.QRect(690, 50, 171, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_puntos.setFont(font)
        self.label_puntos.setObjectName("label_puntos")
        self.label_grafico = QtWidgets.QLabel(self.centralwidget)
        self.label_grafico.setGeometry(QtCore.QRect(1070, 50, 171, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_grafico.setFont(font)
        self.label_grafico.setObjectName("label_grafico")

        self.graph_puntos = QtWidgets.QLabel(self.centralwidget)
        self.graph_puntos.setGeometry(QtCore.QRect(1020, 80, 250, 250))
        self.graph_puntos.setText("")
        self.graph_puntos.setPixmap(QtGui.QPixmap("assets/img_test_detection3.jpeg"))
        self.graph_puntos.setScaledContents(True)
        self.graph_puntos.setObjectName("graph_puntos")

        self.subtitle = QtWidgets.QLabel(self.centralwidget)
        self.subtitle.setGeometry(QtCore.QRect(550, 330, 171, 41))

        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subtitle.setFont(font)
        self.subtitle.setAutoFillBackground(False)
        self.subtitle.setObjectName("subtitle")

        self.label_inter1 = QtWidgets.QLabel(self.centralwidget)
        self.label_inter1.setGeometry(QtCore.QRect(130, 380, 171, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_inter1.setFont(font)
        self.label_inter1.setObjectName("label_inter1")

        self.buttonDefine = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDefine.setGeometry(QtCore.QRect(910, 300, 75, 31))
        self.buttonDefine.setObjectName("buttonDefine")

        self.interpol_1 = QtWidgets.QWidget(self.centralwidget)
        self.interpol_1.setGeometry(QtCore.QRect(10, 410, 400, 240))
        self.interpol_1.setObjectName("interpol_1")

        self.interpol_2 = QtWidgets.QWidget(self.centralwidget)
        self.interpol_2.setGeometry(QtCore.QRect(440, 410, 400, 240))
        self.interpol_2.setObjectName("interpol_2")

        self.label_inter2 = QtWidgets.QLabel(self.centralwidget)
        self.label_inter2.setGeometry(QtCore.QRect(560, 380, 171, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_inter2.setFont(font)
        self.label_inter2.setObjectName("label_inter2")

        self.label_inter3 = QtWidgets.QLabel(self.centralwidget)
        self.label_inter3.setGeometry(QtCore.QRect(960, 380, 211, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_inter3.setFont(font)
        self.label_inter3.setObjectName("label_inter3")

        self.interpol_3 = QtWidgets.QWidget(self.centralwidget)
        self.interpol_3.setGeometry(QtCore.QRect(870, 410, 400, 240))
        self.interpol_3.setObjectName("interpol_3")

        self.text_x1 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_x1.setGeometry(QtCore.QRect(900, 100, 104, 31))
        self.text_x1.setObjectName("text_x1")

        self.label_x1 = QtWidgets.QLabel(self.centralwidget)
        self.label_x1.setGeometry(QtCore.QRect(940, 80, 31, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_x1.setFont(font)
        self.label_x1.setObjectName("label_x1")

        self.text_y1 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_y1.setGeometry(QtCore.QRect(900, 150, 104, 31))
        self.text_y1.setObjectName("text_y1")

        self.label_y1 = QtWidgets.QLabel(self.centralwidget)
        self.label_y1.setGeometry(QtCore.QRect(940, 130, 31, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_y1.setFont(font)
        self.label_y1.setObjectName("label_y1")

        self.label_y2 = QtWidgets.QLabel(self.centralwidget)
        self.label_y2.setGeometry(QtCore.QRect(940, 240, 31, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_y2.setFont(font)
        self.label_y2.setObjectName("label_y2")
        
        self.text_x2 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_x2.setGeometry(QtCore.QRect(900, 210, 104, 31))
        self.text_x2.setObjectName("text_x2")

        self.text_y2 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_y2.setGeometry(QtCore.QRect(900, 260, 104, 31))
        self.text_y2.setObjectName("text_y2")

        self.label_x2 = QtWidgets.QLabel(self.centralwidget)
        self.label_x2.setGeometry(QtCore.QRect(940, 190, 31, 20))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_x2.setFont(font)
        self.label_x2.setObjectName("label_x2")


        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")

        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Load Image
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.menuArchivo.addAction(self.actionLoad_Image)
        #
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #Actions

        #Load Image
        self.actionLoad_Image.triggered.connect(self.loadImage)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Proyecto métodos 2021-I"))
        self.label_original.setText(_translate("MainWindow", "Imagen original"))
        self.buttonProcess.setText(_translate("MainWindow", "Procesar imagen"))
        self.label_hsv.setText(_translate("MainWindow", "Imagen BGR2HSV"))
        self.label_puntos.setText(_translate("MainWindow", "Puntos a interpolar"))
        self.label_grafico.setText(_translate("MainWindow", "Gráfico de puntos"))
        self.subtitle.setText(_translate("MainWindow", "Interpolación"))
        self.label_inter1.setText(_translate("MainWindow", "Interpolación lineal"))
        self.buttonDefine.setText(_translate("MainWindow", "Definir coord"))
        self.label_inter2.setText(_translate("MainWindow", "Interpolación lineal"))
        self.label_inter3.setText(_translate("MainWindow", "Interpolación por splines"))
        self.label_x1.setText(_translate("MainWindow", "x1:"))
        self.label_y1.setText(_translate("MainWindow", "y1:"))
        self.label_y2.setText(_translate("MainWindow", "y2:"))
        self.label_x2.setText(_translate("MainWindow", "x2:"))
        self.menuArchivo.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
    
    #Methods
    def loadImage(self):
        imagePath, _ = QFileDialog.getOpenFileName()
        pixmap = QPixmap(imagePath)
        self.img_original.setPixmap(pixmap)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
